package com.amit.colortodo;

import android.app.*;
import android.os.*;
import android.graphics.Paint;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.content.*;
import android.view.*;
import android.widget.*;
import java.text.*;
import java.util.*;

public class MainActivity extends Activity {
 LinearLayout list; ArrayList<TaskStore.Task> tasks; String size,style;
 final SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault());
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);list=findViewById(R.id.list);size=TaskStore.pref(this,"size","default");style=TaskStore.pref(this,"style","card");findViewById(R.id.addFab).setOnClickListener(v->showAddDialog());findViewById(R.id.viewButton).setOnClickListener(v->showViewDialog());render();}
 @Override protected void onResume(){super.onResume();render();}
 void showAddDialog(){
  LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);form.setPadding(dp(22),dp(8),dp(22),0);
  EditText title=input("Task title"),tag=input("Tag (e.g. Personal)"),notes=input("Notes (optional)");
  TextView due=inputLike("Select due date"); final String[] dueValue={""};
  due.setOnClickListener(v->{Calendar now=Calendar.getInstance();DatePickerDialog picker=new DatePickerDialog(this,(view,y,m,d)->{Calendar selected=Calendar.getInstance();selected.set(y,m,d,0,0,0);selected.set(Calendar.MILLISECOND,0);dueValue[0]=dateFormat.format(selected.getTime());due.setText(new SimpleDateFormat("EEE, d MMM yyyy",Locale.getDefault()).format(selected.getTime()));},now.get(Calendar.YEAR),now.get(Calendar.MONTH),now.get(Calendar.DAY_OF_MONTH));picker.show();});
  RadioGroup priorities=new RadioGroup(this);priorities.setOrientation(LinearLayout.HORIZONTAL);RadioButton high=radio("High"),medium=radio("Medium"),low=radio("Low");medium.setChecked(true);priorities.addView(high);priorities.addView(medium);priorities.addView(low);
  form.addView(title);form.addView(due);form.addView(tag);form.addView(notes);form.addView(priorities);
  AlertDialog dialog=new AlertDialog.Builder(this).setTitle("New task").setView(form).setNegativeButton("Cancel",null).setPositiveButton("Add",null).create();
  dialog.setOnShowListener(x->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String text=title.getText().toString().trim();if(text.isEmpty()){title.setError("Add a title");return;}String p=high.isChecked()?"high":low.isChecked()?"low":"medium";tasks=TaskStore.load(this);tasks.add(new TaskStore.Task(System.currentTimeMillis(),text,p,false,dueValue[0],tag.getText().toString().trim(),notes.getText().toString().trim()));TaskStore.save(this,tasks);dialog.dismiss();render();}));dialog.show();
 }
 void showViewDialog(){String[] sizes={"Compact","Default","Expanded"},styles={"Card","List","Board"};LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(22),0,dp(22),0);Spinner a=new Spinner(this),b=new Spinner(this);a.setAdapter(spinnerAdapter(sizes));b.setAdapter(spinnerAdapter(styles));a.setSelection(size.equals("compact")?0:size.equals("expanded")?2:1);b.setSelection(style.equals("list")?1:style.equals("board")?2:0);box.addView(label("Task size"));box.addView(a);box.addView(label("Layout"));box.addView(b);new AlertDialog.Builder(this).setTitle("View options").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Apply",(d,w)->{size=a.getSelectedItem().toString().toLowerCase();style=b.getSelectedItem().toString().toLowerCase();TaskStore.setPref(this,"size",size);TaskStore.setPref(this,"style",style);render();}).show();}
 ArrayAdapter<String> spinnerAdapter(String[] v){return new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,v);}
 EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setTextColor(getColor(R.color.text_primary));e.setHintTextColor(getColor(R.color.text_muted));e.setSingleLine(true);e.setPadding(dp(12),0,dp(12),0);e.setBackgroundResource(R.drawable.input_bg);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(50));p.setMargins(0,0,0,dp(10));e.setLayoutParams(p);return e;}
 TextView inputLike(String h){TextView t=text(h,16,R.color.text_muted);t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(dp(12),0,dp(12),0);t.setBackgroundResource(R.drawable.input_bg);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(50));p.setMargins(0,0,0,dp(10));t.setLayoutParams(p);return t;}
 RadioButton radio(String s){RadioButton r=new RadioButton(this);r.setText(s);r.setTextColor(getColor(R.color.text_primary));return r;}
 TextView label(String s){TextView t=text(s,12,R.color.text_muted);t.setTypeface(null,Typeface.BOLD);t.setPadding(0,dp(12),0,dp(4));return t;}
 void render(){tasks=TaskStore.load(this);list.removeAllViews();tasks.sort(Comparator.comparingLong(TaskStore::weekStartFor).thenComparing(t->t.done));TextView count=findViewById(R.id.taskCount);int open=0;for(TaskStore.Task t:tasks)if(!t.done)open++;count.setText(open==1?"1 task remaining":open+" tasks remaining");if(tasks.isEmpty()){LinearLayout e=new LinearLayout(this);e.setOrientation(LinearLayout.VERTICAL);e.setGravity(Gravity.CENTER);e.setPadding(dp(20),dp(90),dp(20),dp(40));TextView i=text("✓",30,R.color.accent);i.setGravity(Gravity.CENTER);e.addView(i);TextView h=text("All clear",20,R.color.text_primary);h.setTypeface(null,Typeface.BOLD);h.setGravity(Gravity.CENTER);h.setPadding(0,dp(12),0,dp(5));e.addView(h);TextView s=text("Add a task when something needs your attention.",14,R.color.text_muted);s.setGravity(Gravity.CENTER);e.addView(s);list.addView(e);return;}renderWeeks();}
 void renderWeeks(){LinkedHashMap<Long,List<TaskStore.Task>> groups=new LinkedHashMap<>();for(TaskStore.Task t:tasks)groups.computeIfAbsent(TaskStore.weekStartFor(t),k->new ArrayList<>()).add(t);for(Map.Entry<Long,List<TaskStore.Task>> e:groups.entrySet())list.addView(weekView(e.getKey(),e.getValue()));}
 View weekView(long start,List<TaskStore.Task> weekTasks){LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setPadding(0,0,0,dp(10));String key="week_"+start;boolean expanded=TaskStore.pref(this,key,"true").equals("true");TextView header=text((expanded?"⌄  ":"›  ")+TaskStore.weekLabel(start)+"   "+weekTasks.size(),14,R.color.text_primary);header.setTypeface(null,Typeface.BOLD);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(dp(14),dp(12),dp(14),dp(12));header.setBackground(round(R.color.surface_alt,10));LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setVisibility(expanded?View.VISIBLE:View.GONE);for(TaskStore.Task t:weekTasks)content.addView(taskView(t));header.setOnClickListener(v->{boolean show=content.getVisibility()!=View.VISIBLE;content.setVisibility(show?View.VISIBLE:View.GONE);header.setText((show?"⌄  ":"›  ")+TaskStore.weekLabel(start)+"   "+weekTasks.size());TaskStore.setPref(this,key,String.valueOf(show));});shell.addView(header);shell.addView(content);return shell;}
 View taskView(TaskStore.Task t){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);int vertical=size.equals("compact")?9:size.equals("expanded")?16:13;row.setPadding(dp(10),dp(vertical),dp(12),dp(vertical));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(6),0,0);row.setLayoutParams(lp);row.setBackground(cardBackground(t));row.setElevation(dp(2));View bar=new View(this);GradientDrawable bg=new GradientDrawable();bg.setColor(priorityColor(t));bg.setCornerRadius(dp(4));bar.setBackground(bg);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(dp(4),size.equals("expanded")?dp(78):dp(48));bp.setMargins(0,0,dp(8),0);row.addView(bar,bp);CheckBox check=new CheckBox(this);check.setChecked(t.done);check.setButtonTintList(android.content.res.ColorStateList.valueOf(getColor(R.color.accent)));check.setOnClickListener(v->toggle(t.id));row.addView(check,new LinearLayout.LayoutParams(dp(42),dp(42)));LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);TextView title=text(t.text,size.equals("compact")?15:16,t.done?R.color.text_muted:R.color.text_primary);title.setTypeface(null,Typeface.BOLD);if(t.done)title.setPaintFlags(title.getPaintFlags()|Paint.STRIKE_THRU_TEXT_FLAG);body.addView(title);if(!size.equals("compact")){LinearLayout meta=new LinearLayout(this);meta.setOrientation(LinearLayout.HORIZONTAL);meta.setPadding(0,dp(5),0,0);if(!t.due.isEmpty())meta.addView(chip(TaskStore.displayDate(t.due),R.color.surface_alt));if(!t.tag.isEmpty())meta.addView(chip(t.tag,R.color.tag_surface));meta.addView(chip(cap(t.priority),prioritySurface(t)));body.addView(meta);}if(size.equals("expanded")&&!t.notes.isEmpty()){TextView n=text(t.notes,13,R.color.text_secondary);n.setPadding(0,dp(9),0,0);n.setMaxLines(2);body.addView(n);}row.addView(body,new LinearLayout.LayoutParams(0,-2,1));TextView more=text("⋮",24,R.color.text_muted);more.setGravity(Gravity.CENTER);row.addView(more,new LinearLayout.LayoutParams(dp(34),dp(44)));final long[] last={0};row.setOnClickListener(v->{long now=System.currentTimeMillis();if(now-last[0]<350){toggle(t.id);last[0]=0;}else last[0]=now;});View.OnLongClickListener del=v->{row.animate().alpha(0).translationX(dp(48)).setDuration(160).withEndAction(()->{tasks.removeIf(x->x.id==t.id);TaskStore.save(this,tasks);render();}).start();return true;};row.setOnLongClickListener(del);more.setOnLongClickListener(del);return row;}
 TextView chip(String s,int color){TextView v=text(s,11,R.color.text_secondary);v.setBackground(round(color,20));v.setPadding(dp(8),dp(3),dp(8),dp(3));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.setMargins(0,0,dp(6),0);v.setLayoutParams(p);return v;}
 GradientDrawable cardBackground(TaskStore.Task t){GradientDrawable g=round(t.done?R.color.task_done:R.color.surface,12);g.setStroke(dp(1),getColor(R.color.border));return g;}GradientDrawable round(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(getColor(color));g.setCornerRadius(dp(radius));return g;}int priorityColor(TaskStore.Task t){return getColor(t.priority.equals("high")?R.color.priority_high:t.priority.equals("low")?R.color.priority_low:R.color.priority_medium);}int prioritySurface(TaskStore.Task t){return t.priority.equals("high")?R.color.priority_high_surface:t.priority.equals("low")?R.color.priority_low_surface:R.color.priority_medium_surface;}TextView text(String s,int sp,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(getColor(color));return v;}void toggle(long id){for(TaskStore.Task t:tasks)if(t.id==id)t.done=!t.done;TaskStore.save(this,tasks);render();}String cap(String s){return s.substring(0,1).toUpperCase()+s.substring(1);}int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}
}