package com.amit.colortodo;
import android.content.*;import org.json.*;import java.text.*;import java.util.*;
public class TaskStore {
 public static class Task {public long id;public String text,priority,due,tag,notes;public boolean done;Task(long i,String t,String p,boolean d){this(i,t,p,d,"","","");}Task(long i,String t,String p,boolean d,String due,String tag,String notes){id=i;text=t;priority=p;done=d;this.due=due;this.tag=tag;this.notes=notes;}}
 static ArrayList<Task> load(Context c){ArrayList<Task> out=new ArrayList<>();String s=c.getSharedPreferences("todo",0).getString("tasks","[]");try{JSONArray a=new JSONArray(s);for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);out.add(new Task(o.getLong("id"),o.getString("text"),o.optString("priority","medium"),o.optBoolean("done",false),o.optString("due",""),o.optString("tag",""),o.optString("notes","")));}}catch(Exception ignored){}return out;}
 static void save(Context c,List<Task> ts){JSONArray a=new JSONArray();try{for(Task t:ts){JSONObject o=new JSONObject();o.put("id",t.id);o.put("text",t.text);o.put("priority",t.priority);o.put("done",t.done);o.put("due",t.due);o.put("tag",t.tag);o.put("notes",t.notes);a.put(o);}}catch(Exception ignored){}c.getSharedPreferences("todo",0).edit().putString("tasks",a.toString()).apply();TodoWidget.refresh(c);}
 static String pref(Context c,String key,String fallback){return c.getSharedPreferences("todo",0).getString(key,fallback);}static void setPref(Context c,String key,String value){c.getSharedPreferences("todo",0).edit().putString(key,value).apply();TodoWidget.refresh(c);}
 static long weekStartFor(Task t){Calendar c=Calendar.getInstance();try{if(t.due!=null&&!t.due.isEmpty())c.setTime(new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()).parse(t.due));else c.setTimeInMillis(t.id);}catch(Exception e){c.setTimeInMillis(t.id);}c.setFirstDayOfWeek(Calendar.MONDAY);int dow=c.get(Calendar.DAY_OF_WEEK);int delta=(dow==Calendar.SUNDAY)?-6:Calendar.MONDAY-dow;c.add(Calendar.DAY_OF_MONTH,delta);c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);return c.getTimeInMillis();}
 static String weekLabel(long start){Calendar a=Calendar.getInstance();a.setTimeInMillis(start);Calendar b=(Calendar)a.clone();b.add(Calendar.DAY_OF_MONTH,6);SimpleDateFormat d=new SimpleDateFormat("d MMM",Locale.getDefault()),dy=new SimpleDateFormat("d MMM yyyy",Locale.getDefault());return d.format(a.getTime())+" – "+dy.format(b.getTime());}
 static String displayDate(String iso){try{return new SimpleDateFormat("EEE, d MMM",Locale.getDefault()).format(new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()).parse(iso));}catch(Exception e){return iso;}}
 static boolean isMissed(Task t){if(t==null||t.done||t.due==null||t.due.isEmpty())return false;try{SimpleDateFormat f=new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault());f.setLenient(false);Date due=f.parse(t.due);Calendar dueDay=Calendar.getInstance();dueDay.setTime(due);dueDay.set(Calendar.HOUR_OF_DAY,0);dueDay.set(Calendar.MINUTE,0);dueDay.set(Calendar.SECOND,0);dueDay.set(Calendar.MILLISECOND,0);Calendar today=Calendar.getInstance();today.set(Calendar.HOUR_OF_DAY,0);today.set(Calendar.MINUTE,0);today.set(Calendar.SECOND,0);today.set(Calendar.MILLISECOND,0);return dueDay.before(today);}catch(Exception e){return false;}}
}