package com.amit.colortodo;
import android.app.*; import android.appwidget.*; import android.content.*; import android.widget.*; import java.util.*;
public class TodoWidget extends AppWidgetProvider {
 static final String TOGGLE="com.amit.colortodo.TOGGLE_TASK";
 @Override public void onUpdate(Context c,AppWidgetManager m,int[] ids){for(int id:ids)update(c,m,id);}
 @Override public void onReceive(Context c,Intent i){super.onReceive(c,i);if(TOGGLE.equals(i.getAction())){long id=i.getLongExtra("id",-1);ArrayList<TaskStore.Task> ts=TaskStore.load(c);for(TaskStore.Task t:ts)if(t.id==id)t.done=!t.done;TaskStore.save(c,ts);}}
 static void refresh(Context c){AppWidgetManager m=AppWidgetManager.getInstance(c);ComponentName n=new ComponentName(c,TodoWidget.class);for(int id:m.getAppWidgetIds(n))update(c,m,id);}
 static void update(Context c,AppWidgetManager m,int wid){RemoteViews v=new RemoteViews(c.getPackageName(),R.layout.widget_todo);ArrayList<TaskStore.Task> all=TaskStore.load(c);ArrayList<TaskStore.Task> open=new ArrayList<>();int done=0;for(TaskStore.Task t:all){if(t.done)done++;else open.add(t);}int[] views={R.id.task1,R.id.task2,R.id.task3};for(int x=0;x<3;x++){if(x<open.size()){TaskStore.Task t=open.get(x);v.setViewVisibility(views[x],android.view.View.VISIBLE);v.setTextViewText(views[x],t.text);v.setInt(views[x],"setBackgroundResource",t.priority.equals("high")?R.drawable.bg_high:t.priority.equals("low")?R.drawable.bg_low:R.drawable.bg_medium);Intent ti=new Intent(c,TodoWidget.class).setAction(TOGGLE).putExtra("id",t.id);PendingIntent pi=PendingIntent.getBroadcast(c,(int)t.id,ti,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);v.setOnClickPendingIntent(views[x],pi);}else v.setViewVisibility(views[x],android.view.View.GONE);}
 Intent openApp=new Intent(c,MainActivity.class);v.setOnClickPendingIntent(R.id.widgetTitle,PendingIntent.getActivity(c,9001,openApp,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE));v.setTextViewText(R.id.widgetFooter,done+" completed • Tap task to complete");m.updateAppWidget(wid,v);}
}
