package com.amit.colortodo;
import android.content.*;import android.graphics.Paint;import android.widget.*;import java.util.*;
public class TodoWidgetService extends RemoteViewsService {
 @Override public RemoteViewsFactory onGetViewFactory(Intent intent){return new Factory(getApplicationContext());}
 static class Item {boolean header;long week;TaskStore.Task task;Item(long w){header=true;week=w;}Item(TaskStore.Task t){task=t;week=TaskStore.weekStartFor(t);}}
 static class Factory implements RemoteViewsFactory {
  final Context c;ArrayList<Item> items=new ArrayList<>();Factory(Context c){this.c=c;}public void onCreate(){}
  public void onDataSetChanged(){items.clear();ArrayList<TaskStore.Task> tasks=TaskStore.load(c);tasks.sort(Comparator.comparingLong(TaskStore::weekStartFor).thenComparing(t->t.done));long last=Long.MIN_VALUE;for(TaskStore.Task t:tasks){long w=TaskStore.weekStartFor(t);if(w!=last){items.add(new Item(w));last=w;}if(TaskStore.pref(c,"widget_week_"+w,"true").equals("true"))items.add(new Item(t));}}
  public void onDestroy(){}public int getCount(){return items.size();}
  public RemoteViews getViewAt(int p){if(p<0||p>=items.size())return null;Item i=items.get(p);if(i.header){RemoteViews v=new RemoteViews(c.getPackageName(),R.layout.widget_week_header);boolean open=TaskStore.pref(c,"widget_week_"+i.week,"true").equals("true");v.setTextViewText(R.id.widgetWeekTitle,(open?"⌄  ":"›  ")+TaskStore.weekLabel(i.week));Intent fill=new Intent();fill.setAction(TodoWidget.TOGGLE_WEEK);fill.putExtra(TodoWidget.EXTRA_WEEK,i.week);v.setOnClickFillInIntent(R.id.widgetWeekRow,fill);return v;}TaskStore.Task t=i.task;RemoteViews v=new RemoteViews(c.getPackageName(),R.layout.widget_task_item);v.setTextViewText(R.id.widgetTaskTitle,(t.done?"✓  ":"○  ")+t.text);v.setTextViewText(R.id.widgetTaskMeta,t.due.isEmpty()?"No date":TaskStore.displayDate(t.due));v.setTextColor(R.id.widgetTaskTitle,c.getColor(t.done?R.color.text_muted:R.color.text_primary));v.setInt(R.id.widgetTaskTitle,"setPaintFlags",t.done?Paint.STRIKE_THRU_TEXT_FLAG:0);Intent fill=new Intent();fill.setAction(TodoWidget.TOGGLE);fill.putExtra(TodoWidget.EXTRA_ID,t.id);v.setOnClickFillInIntent(R.id.widgetTaskRow,fill);return v;}
  public RemoteViews getLoadingView(){return null;}public int getViewTypeCount(){return 2;}public long getItemId(int p){Item i=items.get(p);return i.header?-i.week:i.task.id;}public boolean hasStableIds(){return true;}
 }
}